In [1]:
'''Data Cleaning for the Uniform Crime Reporting Statistics - UCR Data Online
http://www.ucrdatatool.gov/

'''

'Data Cleaning for the Uniform Crime Reporting Statistics - UCR Data Online\nhttp://www.ucrdatatool.gov/\n\n'

In [2]:


# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

# Output File (CSV)
output_data_file = "output_data/texas_crime_data.csv"

In [3]:
df_ratings = pd.read_csv("original_data/texas_school_ratings.csv")
df_pop = pd.read_csv("output_data/texas_population.csv")                        
df_crim07 = pd.read_csv("original_data/LocalCrimeOneYearofData07.csv")

df_crime07=df_crim07.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim08 = pd.read_csv("original_data/LocalCrimeOneYearofData08.csv")
df_crime08=df_crim08.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim09 = pd.read_csv("original_data/LocalCrimeOneYearofData09.csv")
df_crime09=df_crim09.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim10 = pd.read_csv("original_data/LocalCrimeOneYearofData10.csv")
df_crime10=df_crim10.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim11 = pd.read_csv("original_data/LocalCrimeOneYearofData11.csv")
df_crime11=df_crim11.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim12 = pd.read_csv("original_data/LocalCrimeOneYearofData12.csv")
df_crime12=df_crim12.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim13 = pd.read_csv("original_data/LocalCrimeOneYearofData13.csv")
df_crime13=df_crim13.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

df_crim14 = pd.read_csv("original_data/LocalCrimeOneYearofData14.csv")
df_crime14=df_crim14.drop(["State", "Months", "Population",  "Murder and nonnegligent Manslaughter", "Legacy rape /1",  "Revised rape /2",  "Robbery",  "Aggravated assault"], axis=1)

data_frames=[df_crime07, df_crime08,df_crime09, df_crime10,df_crime11, df_crime12,df_crime13, df_crime14,]

df_crime07_08=pd.merge(df_crime07, df_crime08, how="left", on="Agency")
df_crime09_10=pd.merge(df_crime09, df_crime10, how="left", on="Agency")
df_crime11_12=pd.merge(df_crime11, df_crime12, how="left", on="Agency")
df_crime13_14=pd.merge(df_crime13, df_crime14, how="left", on="Agency")

df_crime07_10=pd.merge(df_crime07_08, df_crime09_10, how="left", on="Agency")
df_crime11_14=pd.merge(df_crime11_12, df_crime13_14, how="left", on="Agency")
df_crime=pd.merge(df_crime07_10, df_crime11_14, how="left", on="Agency")

In [4]:
df_crime.columns = ["City","2007", "2008", "2009", "2010", "2011","2012","2013","2014"]
df_crime.head(3)

                  City  2007  2008  2009  2010  2011  2012  2013  2014
0  Abilene Police Dept   661   648   658   578   428   472   477   571
1  Addison Police Dept   127    94    90    97    78    72    51    67
2    Alamo Police Dept    55    98   133   154   164   182   164   145

In [5]:
for row in df_crime:
    df_crime["2015"]=round((df_crime["2014"]-df_crime["2013"]+df_crime["2013"]-df_crime["2012"]+df_crime["2012"]-df_crime["2011"])/3+df_crime["2014"])
#     if (df_crime["2015"]<=0):
#         df_crime["2015"]=df_crime["2014"]
        
    df_crime["2016"]=round((df_crime["2015"]-df_crime["2014"]+df_crime["2014"]-df_crime["2013"]+df_crime["2013"]-df_crime["2012"])/3+df_crime["2015"])
    df_crime["2017"]=round((df_crime["2016"]-df_crime["2015"]+df_crime["2015"]-df_crime["2014"]+df_crime["2014"]-df_crime["2013"])/3+df_crime["2016"])

df_crime["Location"]= df_crime.City.str.split(" Pol").str.get(0)
# df_crime

In [6]:
df_ratings["Location"]= df_ratings.name.str.split(",").str.get(0)
df_ratings.head(3)

           name  rating  Location
0   Abilene, TX       6   Abilene
1  Amarillo, TX       6  Amarillo
2    Austin, TX       6    Austin

In [7]:
df_crimed=pd.merge(df_ratings, df_crime, how="left", on="Location")
df_crime=df_crimed.drop(["Location", "City"], axis=1) 
df_crime.columns = ["City","Rating","2007", "2008", "2009", "2010", "2011","2012","2013","2014","2015","2016","2017"]
df_crime

,City,Rating,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,"Abilene, TX",6,661.0,648.0,658.0,578.0,428.0,472.0,477.0,571.0,619.0,668.0,732.0
1,"Amarillo, TX",6,1835.0,1473.0,1580.0,1200.0,1223.0,1278.0,1300.0,1353.0,1396.0,1435.0,1480.0
2,"Austin, TX",6,3871.0,3935.0,4024.0,3790.0,3471.0,3405.0,3123.0,3581.0,3618.0,3689.0,3878.0
3,"Round Rock, TX",6,112.0,128.0,128.0,116.0,115.0,141.0,149.0,140.0,148.0,150.0,150.0
4,"Beaumont, TX",7,1073.0,1015.0,1002.0,900.0,1069.0,1242.0,1225.0,1050.0,1044.0,978.0,896.0
5,"Port Arthur, TX",4,475.0,403.0,433.0,419.0,434.0,344.0,359.0,341.0,310.0,299.0,279.0
6,"Brownsville, TX",4,880.0,634.0,454.0,563.0,500.0,473.0,473.0,558.0,577.0,612.0,658.0
7,"Harlingen, TX",6,334.0,455.0,300.0,399.0,337.0,271.0,264.0,146.0,82.0,19.0,-63.0
8,"College Station, TX",6,251.0,245.0,170.0,220.0,288.0,491.0,379.0,191.0,159.0,48.0,-62.0
9,"Corpus Christi, TX",8,2367.0,2226.0,2365.0,2068.0,1987.0,2057.0,1939.0,2094.0,2130.0,2154.0,2226.0
10,"Dallas, TX",5,13248.0,11420.0,10221.0,9161.0,8330.0,8380.0,8330.0,8457.0,8499.0,8539.0,8609.0
11,"Fort Worth, TX",5,4477.0,4627.0,4245.0,4301.0,4569.0,4525.0,4440.0,4492.0,4466.0,4446.0,4448.0
12,"Arlington, TX",5,2588.0,2262.0,2330.0,1925.0,1874.0,1909.0,1837.0,1854.0,1847.0,1826.0,1822.0
13,"El Paso, TX",6,2574.0,2825.0,2830.0,2861.0,2858.0,2859.0,2522.0,2671.0,2609.0,2526.0,2527.0
14,"Houston, TX",6,24564.0,24779.0,25593.0,22491.0,20892.0,21610.0,20993.0,22008.0,22380.0,22637.0,23185.0
15,"The Woodlands, TX",5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"Sugar Land, TX",10,100.0,138.0,113.0,142.0,96.0,109.0,108.0,99.0,100.0,97.0,93.0
17,"Killeen, TX",9,815.0,885.0,750.0,993.0,815.0,851.0,753.0,846.0,856.0,858.0,893.0
18,"Temple, TX",4,205.0,243.0,180.0,211.0,185.0,202.0,169.0,178.0,176.0,167.0,166.0
19,"Laredo, TX",5,1281.0,1357.0,1294.0,1142.0,1120.0,1036.0,1027.0,976.0,928.0,892.0,847.0
20,"Longview, TX",6,740.0,808.0,713.0,582.0,412.0,463.0,451.0,376.0,364.0,331.0,291.0
21,"Lubbock, TX",5,1953.0,2098.0,2079.0,2001.0,1800.0,1962.0,1829.0,2084.0,2179.0,2251.0,2392.0
22,"McAllen, TX",5,372.0,371.0,348.0,299.0,246.0,166.0,171.0,181.0,159.0,157.0,152.0
23,"Edinburg, TX",6,269.0,285.0,267.0,232.0,282.0,357.0,277.0,296.0,301.0,282.0,284.0
24,"Mission, TX",7,94.0,118.0,124.0,92.0,100.0,104.0,72.0,95.0,93.0,89.0,95.0
25,"Midland, TX",6,343.0,420.0,426.0,407.0,334.0,398.0,350.0,407.0,431.0,442.0,473.0
26,"Odessa, TX",4,529.0,675.0,787.0,726.0,748.0,1103.0,1080.0,1068.0,1175.0,1199.0,1239.0
27,"San Angelo, TX",4,364.0,371.0,365.0,279.0,250.0,269.0,270.0,327.0,353.0,381.0,418.0
28,"San Antonio, TX",5,7327.0,9699.0,7844.0,8434.0,7038.0,6943.0,8828.0,7704.0,7926.0,8254.0,8063.0
29,"New Braunfels, TX",5,158.0,134.0,142.0,121.0,119.0,115.0,147.0,182.0,203.0,232.0,260.0
30,"Sherman, TX",7,146.0,153.0,187.0,180.0,158.0,139.0,120.0,142.0,137.0,136.0,141.0
31,"Denison, TX",5,111.0,112.0,92.0,78.0,91.0,94.0,95.0,88.0,87.0,85.0,82.0
32,"Texarkana, TX",6,506.0,467.0,555.0,527.0,468.0,392.0,329.0,325.0,277.0,239.0,209.0
33,"Tyler, TX",6,652.0,635.0,529.0,656.0,503.0,537.0,376.0,467.0,455.0,428.0,445.0
34,"Victoria, TX",4,346.0,435.0,431.0,388.0,392.0,405.0,397.0,339.0,321.0,293.0,258.0
35,"Waco, TX",4,1139.0,1031.0,883.0,838.0,766.0,635.0,515.0,576.0,513.0,472.0,458.0
36,"Wichita Falls, TX",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_crime["join"]=df_crime.index
df_crime

,City,Rating,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,join
0,"Abilene, TX",6,661.0,648.0,658.0,578.0,428.0,472.0,477.0,571.0,619.0,668.0,732.0,0
1,"Amarillo, TX",6,1835.0,1473.0,1580.0,1200.0,1223.0,1278.0,1300.0,1353.0,1396.0,1435.0,1480.0,1
2,"Austin, TX",6,3871.0,3935.0,4024.0,3790.0,3471.0,3405.0,3123.0,3581.0,3618.0,3689.0,3878.0,2
3,"Round Rock, TX",6,112.0,128.0,128.0,116.0,115.0,141.0,149.0,140.0,148.0,150.0,150.0,3
4,"Beaumont, TX",7,1073.0,1015.0,1002.0,900.0,1069.0,1242.0,1225.0,1050.0,1044.0,978.0,896.0,4
5,"Port Arthur, TX",4,475.0,403.0,433.0,419.0,434.0,344.0,359.0,341.0,310.0,299.0,279.0,5
6,"Brownsville, TX",4,880.0,634.0,454.0,563.0,500.0,473.0,473.0,558.0,577.0,612.0,658.0,6
7,"Harlingen, TX",6,334.0,455.0,300.0,399.0,337.0,271.0,264.0,146.0,82.0,19.0,-63.0,7
8,"College Station, TX",6,251.0,245.0,170.0,220.0,288.0,491.0,379.0,191.0,159.0,48.0,-62.0,8
9,"Corpus Christi, TX",8,2367.0,2226.0,2365.0,2068.0,1987.0,2057.0,1939.0,2094.0,2130.0,2154.0,2226.0,9
10,"Dallas, TX",5,13248.0,11420.0,10221.0,9161.0,8330.0,8380.0,8330.0,8457.0,8499.0,8539.0,8609.0,10
11,"Fort Worth, TX",5,4477.0,4627.0,4245.0,4301.0,4569.0,4525.0,4440.0,4492.0,4466.0,4446.0,4448.0,11
12,"Arlington, TX",5,2588.0,2262.0,2330.0,1925.0,1874.0,1909.0,1837.0,1854.0,1847.0,1826.0,1822.0,12
13,"El Paso, TX",6,2574.0,2825.0,2830.0,2861.0,2858.0,2859.0,2522.0,2671.0,2609.0,2526.0,2527.0,13
14,"Houston, TX",6,24564.0,24779.0,25593.0,22491.0,20892.0,21610.0,20993.0,22008.0,22380.0,22637.0,23185.0,14
15,"The Woodlands, TX",5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
16,"Sugar Land, TX",10,100.0,138.0,113.0,142.0,96.0,109.0,108.0,99.0,100.0,97.0,93.0,16
17,"Killeen, TX",9,815.0,885.0,750.0,993.0,815.0,851.0,753.0,846.0,856.0,858.0,893.0,17
18,"Temple, TX",4,205.0,243.0,180.0,211.0,185.0,202.0,169.0,178.0,176.0,167.0,166.0,18
19,"Laredo, TX",5,1281.0,1357.0,1294.0,1142.0,1120.0,1036.0,1027.0,976.0,928.0,892.0,847.0,19
20,"Longview, TX",6,740.0,808.0,713.0,582.0,412.0,463.0,451.0,376.0,364.0,331.0,291.0,20
21,"Lubbock, TX",5,1953.0,2098.0,2079.0,2001.0,1800.0,1962.0,1829.0,2084.0,2179.0,2251.0,2392.0,21
22,"McAllen, TX",5,372.0,371.0,348.0,299.0,246.0,166.0,171.0,181.0,159.0,157.0,152.0,22
23,"Edinburg, TX",6,269.0,285.0,267.0,232.0,282.0,357.0,277.0,296.0,301.0,282.0,284.0,23
24,"Mission, TX",7,94.0,118.0,124.0,92.0,100.0,104.0,72.0,95.0,93.0,89.0,95.0,24
25,"Midland, TX",6,343.0,420.0,426.0,407.0,334.0,398.0,350.0,407.0,431.0,442.0,473.0,25
26,"Odessa, TX",4,529.0,675.0,787.0,726.0,748.0,1103.0,1080.0,1068.0,1175.0,1199.0,1239.0,26
27,"San Angelo, TX",4,364.0,371.0,365.0,279.0,250.0,269.0,270.0,327.0,353.0,381.0,418.0,27
28,"San Antonio, TX",5,7327.0,9699.0,7844.0,8434.0,7038.0,6943.0,8828.0,7704.0,7926.0,8254.0,8063.0,28
29,"New Braunfels, TX",5,158.0,134.0,142.0,121.0,119.0,115.0,147.0,182.0,203.0,232.0,260.0,29
30,"Sherman, TX",7,146.0,153.0,187.0,180.0,158.0,139.0,120.0,142.0,137.0,136.0,141.0,30
31,"Denison, TX",5,111.0,112.0,92.0,78.0,91.0,94.0,95.0,88.0,87.0,85.0,82.0,31
32,"Texarkana, TX",6,506.0,467.0,555.0,527.0,468.0,392.0,329.0,325.0,277.0,239.0,209.0,32
33,"Tyler, TX",6,652.0,635.0,529.0,656.0,503.0,537.0,376.0,467.0,455.0,428.0,445.0,33
34,"Victoria, TX",4,346.0,435.0,431.0,388.0,392.0,405.0,397.0,339.0,321.0,293.0,258.0,34
35,"Waco, TX",4,1139.0,1031.0,883.0,838.0,766.0,635.0,515.0,576.0,513.0,472.0,458.0,35
36,"Wichita Falls, TX",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36

In [9]:
df_crime["join"][3]=2
df_crime["join"][11]=10
df_crime["join"][12]=10
df_crime["join"][15]=14
df_crime["join"][16]=14
df_crime["join"][29]=28
df_crime["join"][23]=22
df_crime["join"][24]=22
df_crime["join"][18]=17
df_crime["join"][7]=6
df_crime["join"][5]=4
df_crime["join"][31]=30

df_crime_com=df_crime.groupby(["join"]).sum()

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [10]:
df_crime_com["City"]="X"
df_crime_com["City"][2]="Austin-Round Rock, TX"
df_crime_com["City"][10]="Dallas-Fort Worth-Arlington, TX"
df_crime_com["City"][14]="Houston-The Woodlands-Sugar Land, TX"
df_crime_com["City"][28]="San Antonio-New Braunfels, TX"
df_crime_com["City"][22]="McAllen-Edinburg-Mission, TX"
df_crime_com["City"][17]="Killeen-Temple, TX"
df_crime_com["City"][6]="Brownsville-Harlingen, TX"
df_crime_com["City"][4]="Beaumont-Port Arthur, TX"
df_crime_com["City"][9]="Corpus Christi, TX"
df_crime_com["City"][13]="El Paso, TX"

df_crime_com

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/abe/anaconda3/envs/city-analysis/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

,Rating,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,City
join,,,,,,,,,,,,,
0,6,661.0,648.0,658.0,578.0,428.0,472.0,477.0,571.0,619.0,668.0,732.0,X
1,6,1835.0,1473.0,1580.0,1200.0,1223.0,1278.0,1300.0,1353.0,1396.0,1435.0,1480.0,X
2,12,3983.0,4063.0,4152.0,3906.0,3586.0,3546.0,3272.0,3721.0,3766.0,3839.0,4028.0,"Austin-Round Rock, TX"
4,11,1548.0,1418.0,1435.0,1319.0,1503.0,1586.0,1584.0,1391.0,1354.0,1277.0,1175.0,"Beaumont-Port Arthur, TX"
6,10,1214.0,1089.0,754.0,962.0,837.0,744.0,737.0,704.0,659.0,631.0,595.0,"Brownsville-Harlingen, TX"
8,6,251.0,245.0,170.0,220.0,288.0,491.0,379.0,191.0,159.0,48.0,-62.0,X
9,8,2367.0,2226.0,2365.0,2068.0,1987.0,2057.0,1939.0,2094.0,2130.0,2154.0,2226.0,"Corpus Christi, TX"
10,15,20313.0,18309.0,16796.0,15387.0,14773.0,14814.0,14607.0,14803.0,14812.0,14811.0,14879.0,"Dallas-Fort Worth-Arlington, TX"
13,6,2574.0,2825.0,2830.0,2861.0,2858.0,2859.0,2522.0,2671.0,2609.0,2526.0,2527.0,"El Paso, TX"
14,21,24664.0,24917.0,25706.0,22633.0,20988.0,21719.0,21101.0,22107.0,22480.0,22734.0,23278.0,"Houston-The Woodlands-Sugar Land, TX"
17,13,1020.0,1128.0,930.0,1204.0,1000.0,1053.0,922.0,1024.0,1032.0,1025.0,1059.0,"Killeen-Temple, TX"
19,5,1281.0,1357.0,1294.0,1142.0,1120.0,1036.0,1027.0,976.0,928.0,892.0,847.0,X
20,6,740.0,808.0,713.0,582.0,412.0,463.0,451.0,376.0,364.0,331.0,291.0,X
21,5,1953.0,2098.0,2079.0,2001.0,1800.0,1962.0,1829.0,2084.0,2179.0,2251.0,2392.0,X
22,18,735.0,774.0,739.0,623.0,628.0,627.0,520.0,572.0,553.0,528.0,531.0,"McAllen-Edinburg-Mission, TX"
25,6,343.0,420.0,426.0,407.0,334.0,398.0,350.0,407.0,431.0,442.0,473.0,X
26,4,529.0,675.0,787.0,726.0,748.0,1103.0,1080.0,1068.0,1175.0,1199.0,1239.0,X
27,4,364.0,371.0,365.0,279.0,250.0,269.0,270.0,327.0,353.0,381.0,418.0,X
28,10,7485.0,9833.0,7986.0,8555.0,7157.0,7058.0,8975.0,7886.0,8129.0,8486.0,8323.0,"San Antonio-New Braunfels, TX"
30,12,257.0,265.0,279.0,258.0,249.0,233.0,215.0,230.0,224.0,221.0,223.0,X
32,6,506.0,467.0,555.0,527.0,468.0,392.0,329.0,325.0,277.0,239.0,209.0,X
33,6,652.0,635.0,529.0,656.0,503.0,537.0,376.0,467.0,455.0,428.0,445.0,X
34,4,346.0,435.0,431.0,388.0,392.0,405.0,397.0,339.0,321.0,293.0,258.0,X
35,4,1139.0,1031.0,883.0,838.0,766.0,635.0,515.0,576.0,513.0,472.0,458.0,X
36,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,X

In [11]:
df_crime_com=df_crime_com.drop(["Rating"], axis=1)

In [12]:
df_crime_com=df_crime_com[df_crime_com.City != 'X']
# df_crime_com=df_crime_com.set_index('City')
df_crime_com

,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,City
join,,,,,,,,,,,,
2,3983.0,4063.0,4152.0,3906.0,3586.0,3546.0,3272.0,3721.0,3766.0,3839.0,4028.0,"Austin-Round Rock, TX"
4,1548.0,1418.0,1435.0,1319.0,1503.0,1586.0,1584.0,1391.0,1354.0,1277.0,1175.0,"Beaumont-Port Arthur, TX"
6,1214.0,1089.0,754.0,962.0,837.0,744.0,737.0,704.0,659.0,631.0,595.0,"Brownsville-Harlingen, TX"
9,2367.0,2226.0,2365.0,2068.0,1987.0,2057.0,1939.0,2094.0,2130.0,2154.0,2226.0,"Corpus Christi, TX"
10,20313.0,18309.0,16796.0,15387.0,14773.0,14814.0,14607.0,14803.0,14812.0,14811.0,14879.0,"Dallas-Fort Worth-Arlington, TX"
13,2574.0,2825.0,2830.0,2861.0,2858.0,2859.0,2522.0,2671.0,2609.0,2526.0,2527.0,"El Paso, TX"
14,24664.0,24917.0,25706.0,22633.0,20988.0,21719.0,21101.0,22107.0,22480.0,22734.0,23278.0,"Houston-The Woodlands-Sugar Land, TX"
17,1020.0,1128.0,930.0,1204.0,1000.0,1053.0,922.0,1024.0,1032.0,1025.0,1059.0,"Killeen-Temple, TX"
22,735.0,774.0,739.0,623.0,628.0,627.0,520.0,572.0,553.0,528.0,531.0,"McAllen-Edinburg-Mission, TX"
28,7485.0,9833.0,7986.0,8555.0,7157.0,7058.0,8975.0,7886.0,8129.0,8486.0,8323.0,"San Antonio-New Braunfels, TX"

In [13]:
# df_crime_2=df_crime_com.pivot_table(index=["City","2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" ,"2015" ,"2016" ,"2017" ])

city_crime=pd.melt(df_crime_com, 
            id_vars='City', 
            value_vars=["2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" ,"2015" ,"2016" ,"2017"] # list of days of the week
            )
city_crime

                                     City variable    value
0                   Austin-Round Rock, TX     2007   3983.0
1                Beaumont-Port Arthur, TX     2007   1548.0
2               Brownsville-Harlingen, TX     2007   1214.0
3                      Corpus Christi, TX     2007   2367.0
4         Dallas-Fort Worth-Arlington, TX     2007  20313.0
5                             El Paso, TX     2007   2574.0
6    Houston-The Woodlands-Sugar Land, TX     2007  24664.0
7                      Killeen-Temple, TX     2007   1020.0
8            McAllen-Edinburg-Mission, TX     2007    735.0
9           San Antonio-New Braunfels, TX     2007   7485.0
10                  Austin-Round Rock, TX     2008   4063.0
11               Beaumont-Port Arthur, TX     2008   1418.0
12              Brownsville-Harlingen, TX     2008   1089.0
13                     Corpus Christi, TX     2008   2226.0
14        Dallas-Fort Worth-Arlington, TX     2008  18309.0
15                            El Paso, TX     2008   2825.0
16   Houston-The Woodlands-Sugar Land, TX     2008  24917.0
17                     Killeen-Temple, TX     2008   1128.0
18           McAllen-Edinburg-Mission, TX     2008    774.0
19          San Antonio-New Braunfels, TX     2008   9833.0
20                  Austin-Round Rock, TX     2009   4152.0
21               Beaumont-Port Arthur, TX     2009   1435.0
22              Brownsville-Harlingen, TX     2009    754.0
23                     Corpus Christi, TX     2009   2365.0
24        Dallas-Fort Worth-Arlington, TX     2009  16796.0
25                            El Paso, TX     2009   2830.0
26   Houston-The Woodlands-Sugar Land, TX     2009  25706.0
27                     Killeen-Temple, TX     2009    930.0
28           McAllen-Edinburg-Mission, TX     2009    739.0
29          San Antonio-New Braunfels, TX     2009   7986.0
..                                    ...      ...      ...
80                  Austin-Round Rock, TX     2015   3766.0
81               Beaumont-Port Arthur, TX     2015   1354.0
82              Brownsville-Harlingen, TX     2015    659.0
83                     Corpus Christi, TX     2015   2130.0
84        Dallas-Fort Worth-Arlington, TX     2015  14812.0
85                            El Paso, TX     2015   2609.0
86   Houston-The Woodlands-Sugar Land, TX     2015  22480.0
87                     Killeen-Temple, TX     2015   1032.0
88           McAllen-Edinburg-Mission, TX     2015    553.0
89          San Antonio-New Braunfels, TX     2015   8129.0
90                  Austin-Round Rock, TX     2016   3839.0
91               Beaumont-Port Arthur, TX     2016   1277.0
92              Brownsville-Harlingen, TX     2016    631.0
93                     Corpus Christi, TX     2016   2154.0
94        Dallas-Fort Worth-Arlington, TX     2016  14811.0
95                            El Paso, TX     2016   2526.0
96   Houston-The Woodlands-Sugar Land, TX     2016  22734.0
97                     Killeen-Temple, TX     2016   1025.0
98           McAllen-Edinburg-Mission, TX     2016    528.0
99          San Antonio-New Braunfels, TX     2016   8486.0
100                 Austin-Round Rock, TX     2017   4028.0
101              Beaumont-Port Arthur, TX     2017   1175.0
102             Brownsville-Harlingen, TX     2017    595.0
103                    Corpus Christi, TX     2017   2226.0
104       Dallas-Fort Worth-Arlington, TX     2017  14879.0
105                           El Paso, TX     2017   2527.0
106  Houston-The Woodlands-Sugar Land, TX     2017  23278.0
107                    Killeen-Temple, TX     2017   1059.0
108          McAllen-Edinburg-Mission, TX     2017    531.0
109         San Antonio-New Braunfels, TX     2017   8323.0

[110 rows x 3 columns]

In [14]:
city_crimer=city_crime.sort_values(by=['City', 'variable'])
city_crimer.columns = ["City","Year", "Crime"]
city_crimer

                              City  Year   Crime
0            Austin-Round Rock, TX  2007  3983.0
10           Austin-Round Rock, TX  2008  4063.0
20           Austin-Round Rock, TX  2009  4152.0
30           Austin-Round Rock, TX  2010  3906.0
40           Austin-Round Rock, TX  2011  3586.0
50           Austin-Round Rock, TX  2012  3546.0
60           Austin-Round Rock, TX  2013  3272.0
70           Austin-Round Rock, TX  2014  3721.0
80           Austin-Round Rock, TX  2015  3766.0
90           Austin-Round Rock, TX  2016  3839.0
100          Austin-Round Rock, TX  2017  4028.0
1         Beaumont-Port Arthur, TX  2007  1548.0
11        Beaumont-Port Arthur, TX  2008  1418.0
21        Beaumont-Port Arthur, TX  2009  1435.0
31        Beaumont-Port Arthur, TX  2010  1319.0
41        Beaumont-Port Arthur, TX  2011  1503.0
51        Beaumont-Port Arthur, TX  2012  1586.0
61        Beaumont-Port Arthur, TX  2013  1584.0
71        Beaumont-Port Arthur, TX  2014  1391.0
81        Beaumont-Port Arthur, TX  2015  1354.0
91        Beaumont-Port Arthur, TX  2016  1277.0
101       Beaumont-Port Arthur, TX  2017  1175.0
2        Brownsville-Harlingen, TX  2007  1214.0
12       Brownsville-Harlingen, TX  2008  1089.0
22       Brownsville-Harlingen, TX  2009   754.0
32       Brownsville-Harlingen, TX  2010   962.0
42       Brownsville-Harlingen, TX  2011   837.0
52       Brownsville-Harlingen, TX  2012   744.0
62       Brownsville-Harlingen, TX  2013   737.0
72       Brownsville-Harlingen, TX  2014   704.0
..                             ...   ...     ...
37              Killeen-Temple, TX  2010  1204.0
47              Killeen-Temple, TX  2011  1000.0
57              Killeen-Temple, TX  2012  1053.0
67              Killeen-Temple, TX  2013   922.0
77              Killeen-Temple, TX  2014  1024.0
87              Killeen-Temple, TX  2015  1032.0
97              Killeen-Temple, TX  2016  1025.0
107             Killeen-Temple, TX  2017  1059.0
8     McAllen-Edinburg-Mission, TX  2007   735.0
18    McAllen-Edinburg-Mission, TX  2008   774.0
28    McAllen-Edinburg-Mission, TX  2009   739.0
38    McAllen-Edinburg-Mission, TX  2010   623.0
48    McAllen-Edinburg-Mission, TX  2011   628.0
58    McAllen-Edinburg-Mission, TX  2012   627.0
68    McAllen-Edinburg-Mission, TX  2013   520.0
78    McAllen-Edinburg-Mission, TX  2014   572.0
88    McAllen-Edinburg-Mission, TX  2015   553.0
98    McAllen-Edinburg-Mission, TX  2016   528.0
108   McAllen-Edinburg-Mission, TX  2017   531.0
9    San Antonio-New Braunfels, TX  2007  7485.0
19   San Antonio-New Braunfels, TX  2008  9833.0
29   San Antonio-New Braunfels, TX  2009  7986.0
39   San Antonio-New Braunfels, TX  2010  8555.0
49   San Antonio-New Braunfels, TX  2011  7157.0
59   San Antonio-New Braunfels, TX  2012  7058.0
69   San Antonio-New Braunfels, TX  2013  8975.0
79   San Antonio-New Braunfels, TX  2014  7886.0
89   San Antonio-New Braunfels, TX  2015  8129.0
99   San Antonio-New Braunfels, TX  2016  8486.0
109  San Antonio-New Braunfels, TX  2017  8323.0

[110 rows x 3 columns]

In [15]:
#df_pop

In [16]:
city_crimer.to_csv(output_data_file)